services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: multi-platform-aggregator
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "5001:5001"
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma db push &&
      npm run start:prod"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
